### ISSUE TITLE
I2C address

### ISSUE THREAD

**Issue by jadeye** [Seeed-Studio/Accelerometer_And_Gyroscope_LSM6DS3#1]
Hello
Is I2C address configurable or is it the constant address the sensor is on?
I also understand that you can override it after begin() has constructed....
I am trying to connect the sensor to an [Adafruit Feather M0 Bluefruit LE](https://www.adafruit.com/product/2995).
The feather has an I2C pin but I don't know the exact address.
Can you help?
Thanx

**Comment by lanselambor** [comment]
@jadeye It's a const address by 0x6B. Thank you for your question.

**Comment by jadeye** [comment]
:+1:
